name: localization_mapper_annotation
description: A dart package to generate app-localization-mapper that can be parsed dynamic translation keys (as flutter-localizations package does not yet support this).
version: 0.0.2
homepage: https://github.com/coingaming/flutter_localization_mapper
repository: https://github.com/coingaming/flutter_localization_mapper

environment:
  sdk: '>=3.0.0-0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
