name: localization_mapper_generator
description: A dart package to generate app-localization-mapper that can be
  parsed dynamic translation keys (as flutter-localizations package does not yet
  support this).
version: 0.0.3
homepage: https://github.com/coingaming/flutter_localization_mapper
repository: https://github.com/coingaming/flutter_localization_mapper

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  flutter:
    sdk: flutter
  localization_mapper_annotation: ^0.0.2
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
