name: localization_mapper_generator
description: A dart package to generate app-localization-mapper that can be
  parsed dynamic translation keys (as flutter-localizations package does not yet
  support this).
version: 1.0.0-dev.1
homepage: https://github.com/coingaming/flutter_localization_mapper
repository: https://github.com/coingaming/flutter_localization_mapper

environment:
  sdk: '>=3.0.0-0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.5.0
  build: ^2.3.1
  flutter:
    sdk: flutter
  localization_mapper_annotation: ^1.0.0-dev.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
