name: localization_mapper_generator
description: A new Flutter package project.
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  build: ^2.3.1
  flutter:
    sdk: flutter
  localization_mapper_annotation:
    path: ../localization_mapper_annotation/
  source_gen: ^1.2.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null






























